# Generated by Django 2.0 on 2018-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='lat',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
