# Generated by Django 2.0 on 2018-01-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0002_destination_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
