# Generated by Django 2.0 on 2018-01-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0004_auto_20180125_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
