# Generated by Django 2.0 on 2018-01-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0005_auto_20180125_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
