# Generated by Django 2.0 on 2018-01-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0006_auto_20180125_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_lat', models.CharField(max_length=50)),
                ('current_lon', models.CharField(max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_api.Destination')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
