# Generated by Django 2.0 on 2018-01-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0007_destinationprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationprogress',
            old_name='destination',
            new_name='destination_id',
        ),
    ]
