# Generated by Django 2.0 on 2018-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_api', '0008_auto_20180126_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
    ]
